### ISSUE TITLE
Teacher Fund Logo URL

### ISSUE THREAD

**Issue by MRhyne1931** [teacherfund/TeacherFund_raffle#1]
The URL for the logo needs to be updated.  It looks like the branch in TeacherFund_next was updated from master to production.  I have a PR to fix but am getting denied when trying to push my branch.

**Comment by joelwass** [comment]
Treyyyy! You'll probably need to fork the repo to your own profile, push to a branch on that repo, and then issue a PR into this code base

**Comment by MRhyne1931** [comment]
PR submitted. Wasn't able to assign it to anyone

**Comment by MRhyne1931** [comment]
Looks like the URL changed again.  Submitted a new PR.

**Comment by MRhyne1931** [comment]
Issue has been resolved with the latest merge.  Closing.
